PoligonoContiguo: PoligonoContiguoTest.o PoligonoContiguo.o ; g++ PoligonoContiguoTest.o PoligonoContiguo.o -o PoligonoContiguo
PoligonoContiguo.o: PoligonoContiguoTest.cpp ; g++ -c PoligonoContiguoTest.cpp
PoligonoContiguo.o: PoligonoContiguo.cpp ; g++ -c PoligonoContiguo.cpp
clean:
	rm -f  *o PoligonoContiguo