PoligonoContiguo: PoligonoListasEnlazadasTest.o PoligonoListasEnlazadas.o ; g++ PoligonoListasEnlazadasTest.o PoligonoListasEnlazadas.o -o PoligonoListasEnlazadas
PoligonoContiguo.o: PoligonoListasEnlazadasTest.cpp ; g++ -c PoligonoListasEnlazadasTest.cpp
PoligonoContiguo.o: PoligonoListasEnlazadas.cpp ; g++ -c PoligonoListasEnlazadas.cpp
clean:
	rm -f  *o PoligonoListasEnlazadas