poligono: PoligonoTest.o Poligono.o ; g++ PoligonoTest.o Poligono.o -o poligono
PoligonoTest.o: PoligonoTest.cpp ; g++ -c PoligonoTest.cpp
Poligono.o: Poligono.cpp ; g++ -c Poligono.cpp
clean:
	rm -f  *o poligono